name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          key: bun-cache-dir
          path: ~/.bun/install/cache

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint files
        run: bun run lint

      - name: Type check
        run: bun run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: corepack enable
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 22
          cache: bun

      - name: Install dependencies
        run: bun install

      - name: Generate files
        run: bun run build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: corepack enable
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 22
          cache: bun

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
